### ISSUE TITLE
Unexpected end of input while retrieving User properties

### ISSUE THREAD

**Issue by srinadhv9** [whitlockjc/passport-cloudfoundry-uaa-example#1]
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at C:\Users\502362723\git\passport-cloudfoundry-uaa-example\index.js:43:23

**Comment by whitlockjc** [comment]
Can you provide anymore details?

**Comment by srinadhv9** [comment]
I have made changes to oauth-config.json and ran the app. I was able to view home page and got redirected to OIDC login. 

Post login, i got the error. Same OIDC variables worked for a Java OIDC client. 

![image](https://cloud.githubusercontent.com/assets/3818265/13590692/ac0c77de-e4a7-11e5-871b-450b916ec1e2.png)

**Comment by srinadhv9** [comment]
There is an extra "O" in the config file which has caused the issue. Thanks for your reply.

**Comment by whitlockjc** [comment]
The user profile page is expected to be JSON.  If it's not, you need to override `strategy.userProfile` yourself to properly process the document.  It seems you found the issue and fix but I hope this helps.
